/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "nimf-vkeyboardservice.h"
#include "nimf-marshalers-private.h"
#include <string.h>
#include <syslog.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  guint use_gvariant : 1;
  guint emits_changed_signal : 1;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface com.tmaxos.Nimf.VKeyboardService
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:NimfVKeyboardService
 * @title: NimfVKeyboardService
 * @short_description: Generated C code for the com.tmaxos.Nimf.VKeyboardService D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-com-tmaxos-Nimf-VKeyboardService.top_of_page">com.tmaxos.Nimf.VKeyboardService</link> D-Bus interface in C.
 */

/* ---- Introspection data for com.tmaxos.Nimf.VKeyboardService ---- */

static const _ExtendedGDBusArgInfo _nimf_vkeyboard_service_method_info_focus_in_IN_ARG_ic =
{
  {
    -1,
    (gchar *) "ic",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _nimf_vkeyboard_service_method_info_focus_in_IN_ARG_pointers[] =
{
  &_nimf_vkeyboard_service_method_info_focus_in_IN_ARG_ic.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _nimf_vkeyboard_service_method_info_focus_in =
{
  {
    -1,
    (gchar *) "FocusIn",
    (GDBusArgInfo **) &_nimf_vkeyboard_service_method_info_focus_in_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-focus-in",
  FALSE
};

static const _ExtendedGDBusArgInfo _nimf_vkeyboard_service_method_info_focus_out_IN_ARG_ic =
{
  {
    -1,
    (gchar *) "ic",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _nimf_vkeyboard_service_method_info_focus_out_IN_ARG_pointers[] =
{
  &_nimf_vkeyboard_service_method_info_focus_out_IN_ARG_ic.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _nimf_vkeyboard_service_method_info_focus_out =
{
  {
    -1,
    (gchar *) "FocusOut",
    (GDBusArgInfo **) &_nimf_vkeyboard_service_method_info_focus_out_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-focus-out",
  FALSE
};

static const _ExtendedGDBusArgInfo _nimf_vkeyboard_service_method_info_engine_change_IN_ARG_engineid =
{
  {
    -1,
    (gchar *) "engineid",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _nimf_vkeyboard_service_method_info_engine_change_IN_ARG_method =
{
  {
    -1,
    (gchar *) "method",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _nimf_vkeyboard_service_method_info_engine_change_IN_ARG_pointers[] =
{
  &_nimf_vkeyboard_service_method_info_engine_change_IN_ARG_engineid.parent_struct,
  &_nimf_vkeyboard_service_method_info_engine_change_IN_ARG_method.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _nimf_vkeyboard_service_method_info_engine_change =
{
  {
    -1,
    (gchar *) "EngineChange",
    (GDBusArgInfo **) &_nimf_vkeyboard_service_method_info_engine_change_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-engine-change",
  FALSE
};

static const GDBusMethodInfo * const _nimf_vkeyboard_service_method_info_pointers[] =
{
  &_nimf_vkeyboard_service_method_info_focus_in.parent_struct,
  &_nimf_vkeyboard_service_method_info_focus_out.parent_struct,
  &_nimf_vkeyboard_service_method_info_engine_change.parent_struct,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _nimf_vkeyboard_service_interface_info =
{
  {
    -1,
    (gchar *) "com.tmaxos.Nimf.VKeyboardService",
    (GDBusMethodInfo **) &_nimf_vkeyboard_service_method_info_pointers,
    NULL,
    NULL,
    NULL
  },
  "vkeyboard-service",
};


/**
 * nimf_vkeyboard_service_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-com-tmaxos-Nimf-VKeyboardService.top_of_page">com.tmaxos.Nimf.VKeyboardService</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
nimf_vkeyboard_service_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_nimf_vkeyboard_service_interface_info.parent_struct;
}

/**
 * nimf_vkeyboard_service_override_properties:
 * @klass: The class structure for a #GObject derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #NimfVKeyboardService interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
nimf_vkeyboard_service_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * NimfVKeyboardService:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-com-tmaxos-Nimf-VKeyboardService.top_of_page">com.tmaxos.Nimf.VKeyboardService</link>.
 */

/**
 * NimfVKeyboardServiceIface:
 * @parent_iface: The parent interface.
 * @handle_engine_change: Handler for the #NimfVKeyboardService::handle-engine-change signal.
 * @handle_focus_in: Handler for the #NimfVKeyboardService::handle-focus-in signal.
 * @handle_focus_out: Handler for the #NimfVKeyboardService::handle-focus-out signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-com-tmaxos-Nimf-VKeyboardService.top_of_page">com.tmaxos.Nimf.VKeyboardService</link>.
 */

typedef NimfVKeyboardServiceIface NimfVKeyboardServiceInterface;
G_DEFINE_INTERFACE (NimfVKeyboardService, nimf_vkeyboard_service, G_TYPE_OBJECT)

static void
nimf_vkeyboard_service_default_init (NimfVKeyboardServiceIface *iface)
{
	syslog (LOG_DEBUG, G_STRLOC ":%s called on %x\n", G_STRFUNC, iface);
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * NimfVKeyboardService::handle-focus-in:
   * @object: A #NimfVKeyboardService.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_ic: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-tmaxos-Nimf-VKeyboardService.FocusIn">FocusIn()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call nimf_vkeyboard_service_complete_focus_in() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-focus-in",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (NimfVKeyboardServiceIface, handle_focus_in),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * NimfVKeyboardService::handle-focus-out:
   * @object: A #NimfVKeyboardService.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_ic: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-tmaxos-Nimf-VKeyboardService.FocusOut">FocusOut()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call nimf_vkeyboard_service_complete_focus_out() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-focus-out",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (NimfVKeyboardServiceIface, handle_focus_out),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * NimfVKeyboardService::handle-engine-change:
   * @object: A #NimfVKeyboardService.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_engineid: Argument passed by remote caller.
   * @arg_method: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-tmaxos-Nimf-VKeyboardService.EngineChange">EngineChange()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call nimf_vkeyboard_service_complete_engine_change() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-engine-change",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (NimfVKeyboardServiceIface, handle_engine_change),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING);

}

/**
 * nimf_vkeyboard_service_call_focus_in:
 * @proxy: A #NimfVKeyboardServiceProxy.
 * @arg_ic: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-tmaxos-Nimf-VKeyboardService.FocusIn">FocusIn()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call nimf_vkeyboard_service_call_focus_in_finish() to get the result of the operation.
 *
 * See nimf_vkeyboard_service_call_focus_in_sync() for the synchronous, blocking version of this method.
 */
void
nimf_vkeyboard_service_call_focus_in (
    NimfVKeyboardService *proxy,
    const gchar *arg_ic,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "FocusIn",
    g_variant_new ("(s)",
                   arg_ic),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * nimf_vkeyboard_service_call_focus_in_finish:
 * @proxy: A #NimfVKeyboardServiceProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nimf_vkeyboard_service_call_focus_in().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with nimf_vkeyboard_service_call_focus_in().
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
nimf_vkeyboard_service_call_focus_in_finish (
    NimfVKeyboardService *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nimf_vkeyboard_service_call_focus_in_sync:
 * @proxy: A #NimfVKeyboardServiceProxy.
 * @arg_ic: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-tmaxos-Nimf-VKeyboardService.FocusIn">FocusIn()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See nimf_vkeyboard_service_call_focus_in() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
nimf_vkeyboard_service_call_focus_in_sync (
    NimfVKeyboardService *proxy,
    const gchar *arg_ic,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "FocusIn",
    g_variant_new ("(s)",
                   arg_ic),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nimf_vkeyboard_service_call_focus_out:
 * @proxy: A #NimfVKeyboardServiceProxy.
 * @arg_ic: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-tmaxos-Nimf-VKeyboardService.FocusOut">FocusOut()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call nimf_vkeyboard_service_call_focus_out_finish() to get the result of the operation.
 *
 * See nimf_vkeyboard_service_call_focus_out_sync() for the synchronous, blocking version of this method.
 */
void
nimf_vkeyboard_service_call_focus_out (
    NimfVKeyboardService *proxy,
    const gchar *arg_ic,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "FocusOut",
    g_variant_new ("(s)",
                   arg_ic),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * nimf_vkeyboard_service_call_focus_out_finish:
 * @proxy: A #NimfVKeyboardServiceProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nimf_vkeyboard_service_call_focus_out().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with nimf_vkeyboard_service_call_focus_out().
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
nimf_vkeyboard_service_call_focus_out_finish (
    NimfVKeyboardService *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nimf_vkeyboard_service_call_focus_out_sync:
 * @proxy: A #NimfVKeyboardServiceProxy.
 * @arg_ic: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-tmaxos-Nimf-VKeyboardService.FocusOut">FocusOut()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See nimf_vkeyboard_service_call_focus_out() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
nimf_vkeyboard_service_call_focus_out_sync (
    NimfVKeyboardService *proxy,
    const gchar *arg_ic,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "FocusOut",
    g_variant_new ("(s)",
                   arg_ic),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nimf_vkeyboard_service_call_engine_change:
 * @proxy: A #NimfVKeyboardServiceProxy.
 * @arg_engineid: Argument to pass with the method invocation.
 * @arg_method: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-tmaxos-Nimf-VKeyboardService.EngineChange">EngineChange()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call nimf_vkeyboard_service_call_engine_change_finish() to get the result of the operation.
 *
 * See nimf_vkeyboard_service_call_engine_change_sync() for the synchronous, blocking version of this method.
 */
void
nimf_vkeyboard_service_call_engine_change (
    NimfVKeyboardService *proxy,
    const gchar *arg_engineid,
    const gchar *arg_method,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "EngineChange",
    g_variant_new ("(ss)",
                   arg_engineid,
                   arg_method),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * nimf_vkeyboard_service_call_engine_change_finish:
 * @proxy: A #NimfVKeyboardServiceProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nimf_vkeyboard_service_call_engine_change().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with nimf_vkeyboard_service_call_engine_change().
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
nimf_vkeyboard_service_call_engine_change_finish (
    NimfVKeyboardService *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nimf_vkeyboard_service_call_engine_change_sync:
 * @proxy: A #NimfVKeyboardServiceProxy.
 * @arg_engineid: Argument to pass with the method invocation.
 * @arg_method: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-tmaxos-Nimf-VKeyboardService.EngineChange">EngineChange()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See nimf_vkeyboard_service_call_engine_change() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
nimf_vkeyboard_service_call_engine_change_sync (
    NimfVKeyboardService *proxy,
    const gchar *arg_engineid,
    const gchar *arg_method,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "EngineChange",
    g_variant_new ("(ss)",
                   arg_engineid,
                   arg_method),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nimf_vkeyboard_service_complete_focus_in:
 * @object: A #NimfVKeyboardService.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-tmaxos-Nimf-VKeyboardService.FocusIn">FocusIn()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
nimf_vkeyboard_service_complete_focus_in (
    NimfVKeyboardService *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * nimf_vkeyboard_service_complete_focus_out:
 * @object: A #NimfVKeyboardService.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-tmaxos-Nimf-VKeyboardService.FocusOut">FocusOut()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
nimf_vkeyboard_service_complete_focus_out (
    NimfVKeyboardService *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * nimf_vkeyboard_service_complete_engine_change:
 * @object: A #NimfVKeyboardService.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-tmaxos-Nimf-VKeyboardService.EngineChange">EngineChange()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
nimf_vkeyboard_service_complete_engine_change (
    NimfVKeyboardService *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * NimfVKeyboardServiceProxy:
 *
 * The #NimfVKeyboardServiceProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * NimfVKeyboardServiceProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #NimfVKeyboardServiceProxy.
 */

struct _NimfVKeyboardServiceProxyPrivate
{
  GData *qdata;
};

static void nimf_vkeyboard_service_proxy_iface_init (NimfVKeyboardServiceIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (NimfVKeyboardServiceProxy, nimf_vkeyboard_service_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (NimfVKeyboardServiceProxy)
                         G_IMPLEMENT_INTERFACE (NIMF_TYPE_VKEYBOARD_SERVICE, nimf_vkeyboard_service_proxy_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (NimfVKeyboardServiceProxy, nimf_vkeyboard_service_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (NIMF_TYPE_VKEYBOARD_SERVICE, nimf_vkeyboard_service_proxy_iface_init))

#endif
static void
nimf_vkeyboard_service_proxy_finalize (GObject *object)
{
  NimfVKeyboardServiceProxy *proxy = NIMF_VKEYBOARD_SERVICE_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (nimf_vkeyboard_service_proxy_parent_class)->finalize (object);
}

static void
nimf_vkeyboard_service_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
nimf_vkeyboard_service_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
nimf_vkeyboard_service_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  gsize n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_nimf_vkeyboard_service_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], NIMF_TYPE_VKEYBOARD_SERVICE);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, NIMF_TYPE_VKEYBOARD_SERVICE);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
nimf_vkeyboard_service_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  NimfVKeyboardServiceProxy *proxy = NIMF_VKEYBOARD_SERVICE_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_nimf_vkeyboard_service_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_nimf_vkeyboard_service_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
nimf_vkeyboard_service_proxy_init (NimfVKeyboardServiceProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = nimf_vkeyboard_service_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, NIMF_TYPE_VKEYBOARD_SERVICE_PROXY, NimfVKeyboardServiceProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), nimf_vkeyboard_service_interface_info ());
}




static void
nimf_vkeyboard_service_proxy_class_init (NimfVKeyboardServiceProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = nimf_vkeyboard_service_proxy_finalize;
  gobject_class->get_property = nimf_vkeyboard_service_proxy_get_property;
  gobject_class->set_property = nimf_vkeyboard_service_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = nimf_vkeyboard_service_proxy_g_signal;
  proxy_class->g_properties_changed = nimf_vkeyboard_service_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (NimfVKeyboardServiceProxyPrivate));
#endif
}

static void
nimf_vkeyboard_service_proxy_iface_init (NimfVKeyboardServiceIface *iface)
{
}

/**
 * nimf_vkeyboard_service_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-tmaxos-Nimf-VKeyboardService.top_of_page">com.tmaxos.Nimf.VKeyboardService</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call nimf_vkeyboard_service_proxy_new_finish() to get the result of the operation.
 *
 * See nimf_vkeyboard_service_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
nimf_vkeyboard_service_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (NIMF_TYPE_VKEYBOARD_SERVICE_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.tmaxos.Nimf.VKeyboardService", NULL);
}

/**
 * nimf_vkeyboard_service_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nimf_vkeyboard_service_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with nimf_vkeyboard_service_proxy_new().
 *
 * Returns: (transfer full) (type NimfVKeyboardServiceProxy): The constructed proxy object or %NULL if @error is set.
 */
NimfVKeyboardService *
nimf_vkeyboard_service_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return NIMF_VKEYBOARD_SERVICE (ret);
  else
    return NULL;
}

/**
 * nimf_vkeyboard_service_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-tmaxos-Nimf-VKeyboardService.top_of_page">com.tmaxos.Nimf.VKeyboardService</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See nimf_vkeyboard_service_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type NimfVKeyboardServiceProxy): The constructed proxy object or %NULL if @error is set.
 */
NimfVKeyboardService *
nimf_vkeyboard_service_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (NIMF_TYPE_VKEYBOARD_SERVICE_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.tmaxos.Nimf.VKeyboardService", NULL);
  if (ret != NULL)
    return NIMF_VKEYBOARD_SERVICE (ret);
  else
    return NULL;
}


/**
 * nimf_vkeyboard_service_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like nimf_vkeyboard_service_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call nimf_vkeyboard_service_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See nimf_vkeyboard_service_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
nimf_vkeyboard_service_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (NIMF_TYPE_VKEYBOARD_SERVICE_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.tmaxos.Nimf.VKeyboardService", NULL);
}

/**
 * nimf_vkeyboard_service_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nimf_vkeyboard_service_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with nimf_vkeyboard_service_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type NimfVKeyboardServiceProxy): The constructed proxy object or %NULL if @error is set.
 */
NimfVKeyboardService *
nimf_vkeyboard_service_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return NIMF_VKEYBOARD_SERVICE (ret);
  else
    return NULL;
}

/**
 * nimf_vkeyboard_service_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like nimf_vkeyboard_service_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See nimf_vkeyboard_service_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type NimfVKeyboardServiceProxy): The constructed proxy object or %NULL if @error is set.
 */
NimfVKeyboardService *
nimf_vkeyboard_service_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (NIMF_TYPE_VKEYBOARD_SERVICE_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.tmaxos.Nimf.VKeyboardService", NULL);
  if (ret != NULL)
    return NIMF_VKEYBOARD_SERVICE (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * NimfVKeyboardServiceSkeleton:
 *
 * The #NimfVKeyboardServiceSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * NimfVKeyboardServiceSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #NimfVKeyboardServiceSkeleton.
 */

struct _NimfVKeyboardServiceSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_nimf_vkeyboard_service_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  NimfVKeyboardServiceSkeleton *skeleton = NIMF_VKEYBOARD_SERVICE_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  guint num_extra;
  gsize n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], NIMF_TYPE_VKEYBOARD_SERVICE);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, NIMF_TYPE_VKEYBOARD_SERVICE);
	syslog (LOG_DEBUG, G_STRLOC ": %s: signame : %s -> id : %d\n", G_STRFUNC, info->signal_name , signal_id);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_nimf_vkeyboard_service_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  NimfVKeyboardServiceSkeleton *skeleton = NIMF_VKEYBOARD_SERVICE_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_nimf_vkeyboard_service_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_nimf_vkeyboard_service_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  NimfVKeyboardServiceSkeleton *skeleton = NIMF_VKEYBOARD_SERVICE_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_nimf_vkeyboard_service_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _nimf_vkeyboard_service_skeleton_vtable =
{
  _nimf_vkeyboard_service_skeleton_handle_method_call,
  _nimf_vkeyboard_service_skeleton_handle_get_property,
  _nimf_vkeyboard_service_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
nimf_vkeyboard_service_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return nimf_vkeyboard_service_interface_info ();
}

static GDBusInterfaceVTable *
nimf_vkeyboard_service_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_nimf_vkeyboard_service_skeleton_vtable;
}

static GVariant *
nimf_vkeyboard_service_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  NimfVKeyboardServiceSkeleton *skeleton = NIMF_VKEYBOARD_SERVICE_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_nimf_vkeyboard_service_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _nimf_vkeyboard_service_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _nimf_vkeyboard_service_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _nimf_vkeyboard_service_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.tmaxos.Nimf.VKeyboardService", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
nimf_vkeyboard_service_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void nimf_vkeyboard_service_skeleton_iface_init (NimfVKeyboardServiceIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (NimfVKeyboardServiceSkeleton, nimf_vkeyboard_service_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (NimfVKeyboardServiceSkeleton)
                         G_IMPLEMENT_INTERFACE (NIMF_TYPE_VKEYBOARD_SERVICE, nimf_vkeyboard_service_skeleton_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (NimfVKeyboardServiceSkeleton, nimf_vkeyboard_service_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (NIMF_TYPE_VKEYBOARD_SERVICE, nimf_vkeyboard_service_skeleton_iface_init))

#endif
static void
nimf_vkeyboard_service_skeleton_finalize (GObject *object)
{
  NimfVKeyboardServiceSkeleton *skeleton = NIMF_VKEYBOARD_SERVICE_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (nimf_vkeyboard_service_skeleton_parent_class)->finalize (object);
}

static void
nimf_vkeyboard_service_skeleton_init (NimfVKeyboardServiceSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = nimf_vkeyboard_service_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, NIMF_TYPE_VKEYBOARD_SERVICE_SKELETON, NimfVKeyboardServiceSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}


static void nimf_vkeyboard_service_skeleton_constructed(GObject* object){
	GDBusConnection* conn;
	guint id;
	NimfVKeyboardService* service;
  GDBusInterfaceSkeletonClass *skeleton_class;
	GError* err=NULL;
	syslog (LOG_DEBUG, G_STRLOC ": %s: called \n", G_STRFUNC);

	service = (NimfVKeyboardService*) object;
	conn = g_bus_get_sync(G_BUS_TYPE_SESSION , NULL, NULL);
  skeleton_class = NIMF_VKEYBOARD_SERVICE_SKELETON_GET_CLASS ( service);

	id  = g_bus_own_name_on_connection(conn, 
																		NIMF_VKEYBOARD_SERVICE_NAME, 
																			(G_BUS_NAME_OWNER_FLAGS_REPLACE), 
																			NULL,//GBusNameAcquiredCallback name_acquired_handler,
																			NULL,//GBusNameLostCallback
																			NULL,//gpointer
																			NULL);//GDestroyNotify
	syslog (LOG_DEBUG, G_STRLOC ": %s: vtbl : %x  vtbl[0] : %x, method_call %x \n", G_STRFUNC, 
			skeleton_class->get_vtable(service) , 
			skeleton_class->get_vtable(service)[0],
  _nimf_vkeyboard_service_skeleton_handle_method_call);
#if 1
	id = g_dbus_connection_register_object (conn, 
																					NIMF_VKEYBOARD_PATH,
																					skeleton_class->get_info(service),
																					skeleton_class->get_vtable(service),
																					g_object_ref (service),
																					(GDestroyNotify)g_object_unref,
																					NULL);
#else
	if (!g_dbus_interface_skeleton_export ( G_DBUS_INTERFACE_SKELETON (service),
				conn,
				NIMF_VKEYBOARD_PATH,
				&err))
	{
		syslog (LOG_DEBUG, G_STRLOC ": %s: error %s \n", G_STRFUNC, err->message);
		/* handle error */
	}
#endif
	syslog (LOG_DEBUG, G_STRLOC ": %s: service : %x conn : %x id : %d \n", G_STRFUNC, 
			service, conn, id);


}

enum {
	FOCUS_IN,
	FOCUS_OUT,
	ENGINE_CHANGE,
	LAST_SIGNAL,
};

static guint	vkeyboard_signals[LAST_SIGNAL] = { 0 };


static void
nimf_vkeyboard_service_skeleton_class_init (NimfVKeyboardServiceSkeletonClass *klass)
{

	syslog (LOG_DEBUG, G_STRLOC  ": %s: called\n", G_STRFUNC);
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = nimf_vkeyboard_service_skeleton_finalize;
	gobject_class->constructed  = nimf_vkeyboard_service_skeleton_constructed;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = nimf_vkeyboard_service_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = nimf_vkeyboard_service_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = nimf_vkeyboard_service_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = nimf_vkeyboard_service_skeleton_dbus_interface_get_vtable;

	/* define signals  */
	vkeyboard_signals[FOCUS_IN] = 
		g_signal_new ("focus-in",
				G_TYPE_FROM_CLASS (klass),
				G_SIGNAL_RUN_LAST,
				NULL,
				NULL, NULL,
				nimf_cclosure_marshal_VOID__STRING,
				G_TYPE_NONE,
				1,
				G_TYPE_STRING);

	vkeyboard_signals[FOCUS_OUT] = 
		g_signal_new ("focus-out",
				G_TYPE_FROM_CLASS (klass),
				G_SIGNAL_RUN_LAST,
				NULL,
				NULL, NULL,
				nimf_cclosure_marshal_VOID__STRING,
				G_TYPE_NONE,
				1,
				G_TYPE_STRING);
	vkeyboard_signals[ENGINE_CHANGE] = 
		g_signal_new ("engine-change",
				G_TYPE_FROM_CLASS (klass),
				G_SIGNAL_RUN_LAST,
				NULL,
				NULL, NULL,
				nimf_cclosure_marshal_VOID__STRING_STRING,
				G_TYPE_NONE,
				2,
				G_TYPE_STRING,G_TYPE_STRING);


#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (NimfVKeyboardServiceSkeletonPrivate));
#endif
}

gboolean nimf_vkbd_service_engine_change (
NimfVKeyboardService *object,
GDBusMethodInvocation *invocation,
const gchar *arg_engineid,
const gchar *arg_method)
{
	syslog (LOG_DEBUG, G_STRLOC  ": %s: engineid : %s method : %s \n", G_STRFUNC, 
			arg_engineid, arg_method);
	g_signal_emit (object, vkeyboard_signals[ENGINE_CHANGE], 0, arg_engineid,arg_method);
	nimf_vkeyboard_service_complete_engine_change(object,invocation);
	return TRUE;
}

gboolean nimf_vkbd_service_focus_in (
NimfVKeyboardService *object,
GDBusMethodInvocation *invocation,
const gchar *arg_ic)
{
	syslog (LOG_DEBUG,  G_STRLOC ": %s: ic : %s  \n", G_STRFUNC, 
			arg_ic);
	g_signal_emit (object, vkeyboard_signals[FOCUS_IN], 0, arg_ic);
	nimf_vkeyboard_service_complete_focus_in(object,invocation);
	return TRUE;
}

gboolean nimf_vkbd_service_focus_out (
NimfVKeyboardService *object,
GDBusMethodInvocation *invocation,
const gchar *arg_ic)
{
	syslog (LOG_DEBUG, G_STRLOC ": %s: ic : %s  \n", G_STRFUNC, 
			arg_ic);
	g_signal_emit (object, vkeyboard_signals[FOCUS_OUT], 0, arg_ic);
	nimf_vkeyboard_service_complete_focus_out(object,invocation);
	return TRUE;
}


static void
nimf_vkeyboard_service_skeleton_iface_init (NimfVKeyboardServiceIface *iface)
{
	iface->handle_engine_change = nimf_vkbd_service_engine_change;
	iface->handle_focus_in = nimf_vkbd_service_focus_in;
	syslog (LOG_DEBUG, G_STRLOC ": %s: focus_in %x handler %x \n", G_STRFUNC, iface->handle_focus_in, nimf_vkbd_service_focus_in);
	iface->handle_focus_out = nimf_vkbd_service_focus_out;
}

/**
 * nimf_vkeyboard_service_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-com-tmaxos-Nimf-VKeyboardService.top_of_page">com.tmaxos.Nimf.VKeyboardService</link>.
 *
 * Returns: (transfer full) (type NimfVKeyboardServiceSkeleton): The skeleton object.
 */


NimfVKeyboardService *
nimf_vkeyboard_service_skeleton_new (void)
{
	syslog (LOG_DEBUG, G_STRLOC ": %s:called \n", G_STRFUNC);	
	return NIMF_VKEYBOARD_SERVICE (g_object_new (NIMF_TYPE_VKEYBOARD_SERVICE_SKELETON, NULL));
}

